deployment:
  name: testing-microservice
  app: testing-microservice
  replicas: 2
  image: khalidfiyaz/testingservice:latest
  containerPort: 5001

service:
  name: testing-microservice-service
  app: testing-microservice
  port: 80
  targetPort: 5001
  type: LoadBalancer

env:
  microservice_url: "ae2682a406761408bbc312075b874da7-1903900579.us-east-1.elb.amazonaws.com"
  grafana_url: "http://a07c98e7439a74c4cbdcfa449b7dfa60-149929681.us-east-1.elb.amazonaws.com:3000/d/McQOBxqSz/test-results?orgId=1"
  influxdb_url: "http://influxdb:8086"
  influxdb_org: "myorg"
  influxdb_bucket: "mydb"
