apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.app }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      containers:
      - name: {{ .Values.deployment.app }}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        env:
        - name: MICROSERVICE_URL
          value: "{{ .Values.env.microservice_url }}"
        - name: GRAFANA_URL
          value: "{{ .Values.env.grafana_url }}"
        - name: INFLUXDB_URL
          value: "{{ .Values.env.influxdb_url }}"
        - name: INFLUXDB_ORG
          value: "{{ .Values.env.influxdb_org }}"
        - name: INFLUXDB_BUCKET
          value: "{{ .Values.env.influxdb_bucket }}"
