global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'cloned_microservice'
    metrics_path: /metrics
    static_configs:
      - targets: ['cloned_microservice:5001']